language: python
dist: focal  # Ubuntu 20.04 (latest LTS on Travis)

python:
  - "3.10"  # You can change to any version you prefer

before_install:
  - sudo apt update
  - sudo apt-get install -y python3-dev

install:
  - pip install --upgrade pip
  - pip install telebot flask aiogram pymango aiohttp python-telegram-bot

before_script:
  - chmod +x *

script:
  - python3 spidy.py
  